[package]
name = "AccountBasedPrivacy"
type = "contract"
authors = [""]

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v1.2.0", directory="noir-projects/aztec-nr/aztec" }